spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/poem-generator
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
    show-sql: true

  ai:
    mistral:
      host: https://api.mistral.ai
      api-key:
      model: mistral-large-latest

